### Avaliação dos dados

- gdf.shape
- gdf.columns
- gdf.crs
- gdf.isna().sum()
- gdf.geometry.is_valid.value_counts()

Itens a serem verificados:
- nmr de setores
- codigos duplicados
- valores nulos
- CRS
- população = 0
- setores sem info de renda
- geometrias invalidas
- cobertura territorial
- tipos de variaveis

ex output:
- Setores Porto Alegre: 2.989
- Setores com população: 2.944
- Setores sem renda: 31
- Geometrias inválidas: 4
- CRS original: EPSG:4674

In [1]:
from pathlib import Path

import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt

In [2]:
PROJECT_ROOT = Path.cwd().parent

PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

print(PROCESSED_DIR)

c:\Users\simon\Documents\GitHub\SegregacaoPoa\data\processed

In [3]:
for arquivo in PROCESSED_DIR.iterdir():
    print(arquivo.name)

bairros_poa.gpkg
limite_poa.gpkg
renda_setores_poa.csv
setores_poa.gpkg

In [4]:
renda_setores = pd.read_csv(
    PROCESSED_DIR / "renda_setores_poa.csv",
    dtype={"CD_SETOR": str}
)

setores = gpd.read_file(
    PROCESSED_DIR / "setores_poa.gpkg",
    layer="setores_poa"
)

bairros = gpd.read_file(
    PROCESSED_DIR / "bairros_poa.gpkg",
    layer="bairros_poa"
)

limite = gpd.read_file(
    PROCESSED_DIR / "limite_poa.gpkg",
    layer="limite_poa"
)

In [5]:
display(renda_setores.head())
display(setores.head())
display(bairros.head())
display(limite.head())

          CD_SETOR   V06004  V06001
0  431490205000001  5761.34   115.0
1  431490205000002  6166.13    77.0
2  431490205000003  6157.23   233.0
3  431490205000004  7754.60   143.0
4  431490205000005  4420.22   264.0

,CD_SETOR,SITUACAO,CD_SIT,CD_TIPO,AREA_KM2,CD_REGIAO,NM_REGIAO,CD_UF,NM_UF,CD_MUN,...,v0001,v0002,v0003,v0004,v0005,v0006,v0007,V06004,V06001,geometry
0,431490205000001,Urbana,1,0,0.081170,4,Sul,43,Rio Grande do Sul,4314902,...,218.0,181.0,177.0,4.0,1.8,0.0522,115.0,5761.34,115.0,"MULTIPOLYGON (((478127.552 6677839.463, 478122..."
1,431490205000002,Urbana,1,0,0.015490,4,Sul,43,Rio Grande do Sul,4314902,...,133.0,109.0,109.0,0.0,1.7,0.0256,78.0,6166.13,77.0,"MULTIPOLYGON (((478038.102 6677695.266, 478031..."
2,431490205000003,Urbana,1,0,0.007422,4,Sul,43,Rio Grande do Sul,4314902,...,448.0,342.0,342.0,0.0,1.9,0.0086,233.0,6157.23,233.0,"MULTIPOLYGON (((478031.207 6677695.529, 477870..."
3,431490205000004,Urbana,1,0,0.113515,4,Sul,43,Rio Grande do Sul,4314902,...,240.0,205.0,203.0,2.0,1.7,0.0629,143.0,7754.60,143.0,"MULTIPOLYGON (((478353.662 6678190.066, 478252..."
4,431490205000005,Urbana,1,0,0.066469,4,Sul,43,Rio Grande do Sul,4314902,...,435.0,414.0,413.0,1.0,1.6,0.0530,264.0,4420.22,264.0,"MULTIPOLYGON (((478341.134 6678014.409, 478337..."

,CD_REGIAO,NM_REGIAO,CD_UF,NM_UF,CD_MUN,NM_MUN,CD_DIST,NM_DIST,CD_SUBDIST,NM_SUBDIST,...,NM_CONCURB,AREA_KM2,v0001,v0002,v0003,v0004,v0005,v0006,v0007,geometry
0,4,Sul,43,Rio Grande do Sul,4314902,Porto Alegre,431490205,Porto Alegre,43149020500,None,...,Porto Alegre/RS,1.398208,8749,4605,4592,13,2.4,0.0331,3658,"MULTIPOLYGON (((480241.259 6673551.47, 480277...."
1,4,Sul,43,Rio Grande do Sul,4314902,Porto Alegre,431490205,Porto Alegre,43149020500,None,...,Porto Alegre/RS,2.617060,1522,1241,1240,1,1.8,0.0427,844,"MULTIPOLYGON (((478041.857 6676413.605, 478060..."
2,4,Sul,43,Rio Grande do Sul,4314902,Porto Alegre,431490205,Porto Alegre,43149020500,None,...,Porto Alegre/RS,0.760016,13014,10209,10185,24,1.7,0.0581,7710,"MULTIPOLYGON (((478473.546 6676369.423, 478402..."
3,4,Sul,43,Rio Grande do Sul,4314902,Porto Alegre,431490205,Porto Alegre,43149020500,None,...,Porto Alegre/RS,2.299899,27961,17613,17584,29,2,0.0338,14038,"MULTIPOLYGON (((478950.709 6675121.961, 478961..."
4,4,Sul,43,Rio Grande do Sul,4314902,Porto Alegre,431490205,Porto Alegre,43149020500,None,...,Porto Alegre/RS,0.601110,774,519,517,2,1.9,0.0482,394,"MULTIPOLYGON (((479071.669 6676730.949, 479038..."

                                            geometry
0  MULTIPOLYGON (((477228.121 6666354.536, 477202...

In [6]:
print("RENDA:")
print(renda_setores.columns.tolist())

print("\nSETORES:")
print(setores.columns.tolist())

print("\nBAIRROS:")
print(bairros.columns.tolist())

print("\nLIMITE:")
print(limite.columns.tolist())

RENDA:
['CD_SETOR', 'V06004', 'V06001']

SETORES:
['CD_SETOR', 'SITUACAO', 'CD_SIT', 'CD_TIPO', 'AREA_KM2', 'CD_REGIAO', 'NM_REGIAO', 'CD_UF', 'NM_UF', 'CD_MUN', 'NM_MUN', 'CD_DIST', 'NM_DIST', 'CD_SUBDIST', 'NM_SUBDIST', 'CD_BAIRRO', 'NM_BAIRRO', 'CD_NU', 'NM_NU', 'CD_FCU', 'NM_FCU', 'CD_AGLOM', 'NM_AGLOM', 'CD_RGINT', 'NM_RGINT', 'CD_RGI', 'NM_RGI', 'CD_CONCURB', 'NM_CONCURB', 'v0001', 'v0002', 'v0003', 'v0004', 'v0005', 'v0006', 'v0007', 'V06004', 'V06001', 'geometry']

BAIRROS:
['CD_REGIAO', 'NM_REGIAO', 'CD_UF', 'NM_UF', 'CD_MUN', 'NM_MUN', 'CD_DIST', 'NM_DIST', 'CD_SUBDIST', 'NM_SUBDIST', 'CD_BAIRRO', 'NM_BAIRRO', 'CD_RGINT', 'NM_RGINT', 'CD_RGI', 'NM_RGI', 'CD_CONCURB', 'NM_CONCURB', 'AREA_KM2', 'v0001', 'v0002', 'v0003', 'v0004', 'v0005', 'v0006', 'v0007', 'geometry']

LIMITE:
['geometry']

In [7]:
print("Renda:", renda_setores.shape)
print("Setores:", setores.shape)
print("Bairros:", bairros.shape)
print("Limite:", limite.shape)

Renda: (2713, 3)
Setores: (2744, 39)
Bairros: (94, 27)
Limite: (1, 1)

In [8]:
print("CRS setores:", setores.crs)
print("CRS bairros:", bairros.crs)
print("CRS limite:", limite.crs)

CRS setores: EPSG:31982
CRS bairros: EPSG:31982
CRS limite: EPSG:31982